<a href="https://colab.research.google.com/github/451091958/llllsw/blob/main/matrix_completion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x=np.array([
        [5, 0, 0, 3 , 2],
        [0, 5, 3, 0 , 5],
        [5, 3, 0, 0 , 0],
        [3, 0, 5, 4 , 0],
    ], dtype=np.float)
x[x==0]=np.nan
print(x)

[[ 5. nan nan  3.  2.]
 [nan  5.  3. nan  5.]
 [ 5.  3. nan nan nan]
 [ 3. nan  5.  4. nan]]


In [3]:
m=len(x)
k=len(x[0])
print(m,k)#     m k取x矩阵的行列长宽

4 5


In [4]:
h=3       #超参数h，要求小于m和k
U=np.random.rand(m,h)
V=np.random.rand(k,h)
print(U)
print(V)

[[0.28078041 0.05668749 0.41659871]
 [0.65063131 0.753598   0.63510203]
 [0.98412639 0.70500721 0.5448829 ]
 [0.31101042 0.55255489 0.65436021]]
[[0.77601483 0.84920876 0.60321767]
 [0.24027773 0.11646177 0.45280956]
 [0.93637111 0.55440246 0.73251889]
 [0.31778716 0.45881623 0.61943892]
 [0.96254571 0.28801985 0.7406683 ]]


In [5]:
def loss(X,U,V):
    L=0.0
    for i in range(len(x)):
        for j in range(len(x[0])):
            if x[i][j]==x[i][j]:             
                L=L+(x[i][j]-np.dot(U[i, :],V[j, :].T))**2
    return L

In [9]:
for run in range(1,6000):
    for i in range(len(x)):
        for j in range(len(x[0])):
            eij=0
            if x[i][j]==x[i][j]:
                eij=x[i][j]-np.dot(U[i, :],V[j, :].T)
                U[i, :] += 0.001 * 2 * eij * V[j, :].T 
                V[j, :] += 0.001 * 2 * eij * U[i, :] 
    
    if run%600==1:
        print(loss(x,U,V))

6.218487915274966e-11
1.8907202842380376e-11
5.7487856954563346e-12
1.7479471182904458e-12
5.314743023078794e-13
1.6159847763742395e-13
4.9135214589249924e-14
1.4939938025554956e-14
4.542604881026649e-15
1.3812148415106737e-15


In [11]:
print(x)
xhat=np.dot(U,V.T)
print(xhat)
for i in range(len(x)):
    for j in range(len(x[0])):
        xhat[i][j]=round(xhat[i][j])
        if xhat[i][j]>5:
          xhat[i][j]=5
print(xhat)

[[ 5. nan nan  3.  2.]
 [nan  5.  3. nan  5.]
 [ 5.  3. nan nan nan]
 [ 3. nan  5.  4. nan]]
[[4.99999999 2.96237291 2.47314773 3.         2.00000001]
 [6.93491625 5.00000001 3.         4.2950685  4.99999999]
 [5.00000001 2.99999999 1.8847134  2.78199125 2.63212374]
 [3.         4.1931874  5.         4.         2.81536955]]
[[5. 3. 2. 3. 2.]
 [5. 5. 3. 4. 5.]
 [5. 3. 2. 3. 3.]
 [3. 4. 5. 4. 3.]]


公式来源
https://www.cnblogs.com/wuliytTaotao/p/10814770.html



