<a href="https://colab.research.google.com/github/451091958/llllsw/blob/main/matrix_completion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x=np.array([
        [5, 0, 0, 3 , 2],
        [0, 5, 3, 0 , 5],
        [5, 3, 0, 0 , 0],
        [3, 0, 5, 4 , 0],
    ], dtype=np.float)
x[x==0]=np.nan
print(x)

[[ 5. nan nan  3.  2.]
 [nan  5.  3. nan  5.]
 [ 5.  3. nan nan nan]
 [ 3. nan  5.  4. nan]]


In [3]:
m=len(x)
k=len(x[0])
print(m,k)#     m k取x矩阵的行列长宽

4 5


In [4]:
h=3       #超参数h，要求小于m和k
U=np.random.rand(m,h)
V=np.random.rand(k,h)
print(U)
print(V)

[[0.92861548 0.19185827 0.28510407]
 [0.04441584 0.7730483  0.39038581]
 [0.22647762 0.44548638 0.49593484]
 [0.14324002 0.2954096  0.58025435]]
[[0.95856581 0.63765021 0.59748054]
 [0.21316592 0.46958577 0.30352947]
 [0.91748678 0.98049078 0.60497153]
 [0.49442978 0.43940386 0.52623609]
 [0.7046323  0.96790588 0.10357078]]


In [5]:
def loss(X,U,V):
    L=0.0
    for i in range(len(x)):
        for j in range(len(x[0])):
            if x[i][j]==x[i][j]:             
                L=L+(x[i][j]-np.dot(U[i, :],V[j, :].T))**2
    return L

In [6]:
for run in range(1,6000):
    for i in range(len(x)):
        for j in range(len(x[0])):
            eij=0
            if x[i][j]==x[i][j]:
                eij=x[i][j]-np.dot(U[i, :],V[j, :].T)
                U[i, :] += 0.001 * 2 * eij * V[j, :].T 
                V[j, :] += 0.001 * 2 * eij * U[i, :] 
    
    if run%600==1:
        print(loss(x,U,V))

120.69018482574272
0.20992356447636593
7.204376642088691e-05
3.297744568089896e-08
3.8545316792835785e-11
6.781530315813648e-14
1.281945248653219e-16
2.4470163632423784e-19
4.677639711157337e-22
8.84040326094774e-25


In [7]:
print(x)
xhat=np.dot(U,V.T)
print(xhat)
for i in range(len(x)):
    for j in range(len(x[0])):
        xhat[i][j]=round(xhat[i][j])
        if xhat[i][j]>5:
          xhat[i][j]=5
print(xhat)

[[ 5. nan nan  3.  2.]
 [nan  5.  3. nan  5.]
 [ 5.  3. nan nan nan]
 [ 3. nan  5.  4. nan]]
[[5.         1.7473934  4.51547569 3.         2.        ]
 [2.26687043 5.         3.         3.19202989 5.        ]
 [5.         3.         5.26593319 3.81583642 3.06892126]
 [3.         3.91753834 5.         4.         3.4651406 ]]
[[5. 2. 5. 3. 2.]
 [2. 5. 3. 3. 5.]
 [5. 3. 5. 4. 3.]
 [3. 4. 5. 4. 3.]]


公式来源
https://www.cnblogs.com/wuliytTaotao/p/10814770.html



